# This file describes the network interfaces available on your system
# For more information, see netplan(5).
---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp6s0:
      dhcp4: false
    enx0050b61edace:
      dhcp4: false
    enp0s31f6:
      dhcp4: false
  bridges:
    br0:
      addresses:
        - 192.168.37.60/24
      gateway4: 192.168.37.1
      nameservers:
        search:
          - ad.mil.ufl.edu
        addresses:
          - 192.168.37.1
          - 192.168.37.31
          - 192.168.37.32

      interfaces:
        - enp6s0
        - enx0050b61edace
        - enp0s31f6
