#!/bin/bash
# Completes procedure to setup an individual linux user for MIL's development environment.
# To be run after system_install has been run.
set -euo pipefail

# It is generally assumed that users will use ~/catkin_ws, but
# setting CATKIN_WS prior to running this script will change this behavior.
if [[ -z ${CATKIN_DIR:-""} ]]; then
    CATKIN_DIR="$HOME/catkin_ws"
    echo "Using default catkin workspace $CATKIN_DIR"
else
    echo "Using custom catkin workspace $CATKIN_DIR"
fi
CATKIN_SOURCE_DIR="$CATKIN_DIR/src"
MIL_REPO_DIR="$CATKIN_SOURCE_DIR/mil"

# Clone repositry
mil_user_install_dependencies()
{
  sudo apt update
  sudo apt install -y \
    git \
    tmux \
    vim \
    awscli \
    net-tools \
    cifs-utils \
    nmap
}

# Add line to user's bashrc which source the repo's setup files
# This allows us to update aliases, environment variables, etc
mil_user_setup_bashrc()
{
  # Line(s) added to ~/.bashrc
  # Note that for backwards compatiblity this should not be changed
  # unless you have a very good reason.
  BASH_RC_LINES=". $MIL_REPO_DIR/scripts/setup.bash"

  # Add the line(s) to bashrc if not already present
  if grep -Fq "$BASH_RC_LINES" ~/.bashrc
  then
    echo "milrc is already sourced in ~/.bashrc, skipping"
  else
    echo "Adding source of milrc to ~/.bashrc"
    echo "" >> ~/.bashrc
    echo "# Setup enviroment for MIL developement" >> ~/.bashrc
    echo "$BASH_RC_LINES" >> ~/.bashrc
  fi
}

# Sets up the catkin workspace so that user can build
# If the repo is already cloned here, it will build the MIL code
mil_user_setup_init_catkin()
{
  mkdir -p $CATKIN_SOURCE_DIR
  catkin_init_workspace $CATKIN_SOURCE_DIR
  catkin_make -C $CATKIN_DIR
}

mil_user_install_dependencies
mil_user_setup_bashrc
set +u
. /opt/ros/melodic/setup.bash
set -u
mil_user_setup_init_catkin

sudo cp /dynparam /opt/ros/melodic/lib/dynamic_reconfigure/dynparam
