#!/bin/bash
# This script is run by the navigator user when the main NaviGator computer starts.
USER="indyav"

# Location of proprietary repositories
SDGPS_DIR="/home/$USER/sdgps/sdgps_current"

# Command to connect to sylphase GPS/INS
SDGPS="$SDGPS_DIR/build/main"
ANTENNA_POSITION="[0.915,0,0]"
GPS_CMD="(cd $SDGPS_DIR;sudo $SDGPS sylphase-usbgpsimu2 --antenna-position '$ANTENNA_POSITION' --use-imu1 ! tracker ! kf2 --decimation 10 ! listen-solution-tcp 1234)"

ROSCORE="roscore"

# Name of tmux session
SESSION="sdgps"

# Tmux command
TMUX="tmux"

# Exit if script is run for second time
if $TMUX has-session -t $SESSION 2> /dev/null; then
    echo "$SESSION already created, aborting"
    exit 0
fi

# Start tmux session
$TMUX new-session -d -s ${SESSION} -n "roscore"

# Start roscore in first window
$TMUX send-keys -t $SESSION:0 "$ROSCORE" C-m

# Start GPS driver in second window
$TMUX new-window -t $SESSION:1 -n "sdgps"
$TMUX send-keys -t $SESSION:1 "$GPS_CMD" C-m
