#!/bin/bash
set -euo pipefail

mil_system_install()
{
  sudo apt install -y $@
}

# Update apt
sudo apt update

# System dependencies
mil_system_install apt-utils
mil_system_install --no-install-recommends \
  ca-certificates \
  curl \
  tzdata \
  dirmngr \
  gnupg2 \
  lsb-release \
  python2 \
  ruby \
  wget \
  vim \
  expect

# Attempt to install vcstool using apt-get or pip if apt-get does not work
sudo apt install -y python3-vcstool || sudo pip3 install -U vcstool

# Install Python 2 pip
sudo add-apt-repository universe
sudo apt update
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
python2 get-pip.py

# ROS apt source
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
# Install Gazebo apt source
sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -sc) main" > /etc/apt/sources.list.d/gazebo-stable.list' \

# Pull ROS apt key
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
# Pull gazebo apt key
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key D2486D2DD83DB69272AFE98867170598AF249743

# Pull Gazebo apt key
wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
# Update apt again and install ros
sudo apt update

mil_system_install ros-noetic-desktop-full
# Install additional dependencies not bundled by default with ros
# Please put each on a new line for readability
mil_system_install \
  ros-melodic-serial \
  ros-melodic-tf2-sensor-msgs \
  ros-melodic-geographic-msgs \
  ros-melodic-velodyne \
  ros-melodic-usb-cam \
  ros-melodic-joy \
  ros-melodic-spacenav-node \
  ros-melodic-velodyne-simulator \
  ros-melodic-hector-gazebo-plugins \
  ros-melodic-joy \
  ros-melodic-joy-teleop \
  ros-melodic-key-teleop \
  ros-melodic-robot-localization \
  ros-melodic-teleop-tools \
  ros-melodic-teleop-twist-keyboard \
  ros-melodic-ros-control \
  ros-melodic-ros-controllers \
  python-pip \
  clang-format-3.9
sudo pip install \
  tqdm \
  scipy \
  sklearn \
  pandas \

pip install --upgrade pip
pip2 install tsp_solver2
pip2 install Pillow
pip2 install pyyaml


# Documentation dependencies
mil_system_install  python3-pip python-setuptools

# Install Python 3 ROS node dependencies
sudo pip3 install -q \
  sphinx \
  recommonmark \
  sphinx_rtd_theme \
  numpy \
  matplotlib \
  rospkg \
  pyyaml

# Initialize rosdep
sudo apt-get install python3-rosdep
sudo rosdep init
rosdep update
