#!/bin/bash
set -euo pipefail

mil_system_install()
{
  sudo apt install -y $@
}

# Update apt
sudo apt update

# Installation for virtual machines
# Installs the apt-add-repository command
sudo apt-get install software-properties-common -y

# Installs keyboard config without prompting for input
sudo DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration -y # Weird bug

# System dependencies
mil_system_install apt-utils
mil_system_install --no-install-recommends \
  ca-certificates \
  curl \
  tzdata \
  dirmngr \
  gnupg2 \
  lsb-release \
  python3 \
  python3-pip \
  python2 \
  ruby \
  wget \
  vim \
  expect

# Attempt to install vcstool using apt-get or pip if apt-get does not work
sudo apt install -y python3-vcstool || sudo pip3 install -U vcstool

# Install Python 2 pip
sudo add-apt-repository universe
sudo apt update
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
python2 get-pip.py
rm get-pip.py

# ROS apt source
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
# Install Gazebo apt source
sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -sc) main" > /etc/apt/sources.list.d/gazebo-stable.list' \

# Pull ROS apt key
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
# Pull gazebo apt key
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key D2486D2DD83DB69272AFE98867170598AF249743

# Pull Gazebo apt key
wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
# Update apt again and install ros
sudo apt update

mil_system_install ros-noetic-desktop-full
# Install additional dependencies not bundled by default with ros
# Please put each on a new line for readability
mil_system_install \
  ros-noetic-serial \
  ros-noetic-tf2-sensor-msgs \
  ros-noetic-geographic-msgs \
  ros-noetic-velodyne \
  ros-noetic-usb-cam \
  ros-noetic-joy \
  ros-noetic-spacenav-node \
  ros-noetic-velodyne-simulator \
  ros-noetic-hector-gazebo-plugins \
  ros-noetic-joy-teleop \
  ros-noetic-key-teleop \
  ros-noetic-robot-localization \
  ros-noetic-teleop-tools \
  ros-noetic-teleop-twist-keyboard \
  ros-noetic-ros-control \
  ros-noetic-ros-controllers \

# Documentation dependencies
mil_system_install  python3-pip python3-setuptools

# Install Python 3 dependencies
sudo pip3 install -r requirements.txt

# Link a python executable to Python 2 for temporary backwards compatibility
if which python > /dev/null 2>&1;
then
    echo "Python executable already exists."
else
    echo "Attempting to symlink python2 to python..."
    sudo ln -s /usr/bin/python2 /usr/bin/python
    echo "Symlinked Python executable! Nice!"
fi

# Initialize rosdep
sudo apt-get install python3-rosdep

# Update rosdep
sudo rm -rf /etc/ros/rosdep/sources.list.d/* # Delete this file first - if not deleted, error could be thrown
sudo rosdep init
sudo rosdep update
