#!/usr/bin/env python
import rospy
import sys
import argparse
from sub8_alarm import single_alarm
from sub8_ros_tools.init_helpers import wait_for_subscriber


if __name__ == '__main__':
    usage_msg = ("Pass the name of an alarm, and this script will raise it")
    desc_msg = "Raise an alarm"

    parser = argparse.ArgumentParser(usage=usage_msg, description=desc_msg)
    parser.add_argument(dest='alarm_name',
                        help="The alarm name you'd like to raise")

    args = parser.parse_args(sys.argv[1:])
    rospy.init_node('alarm_raise')
    broadcaster, alarm = single_alarm(args.alarm_name, action_required=True)

    rospy.logwarn("Creating alarm publisher....")
    # Wait until subscription lands
    rospy.sleep(0.5)
    alarm.raise_alarm()
