#!/system/bin/sh
set -euo pipefail

source /data/data/com.termux/files/home/.termux/boot/prefix.sh

mkdir -p $PREFIX/ubuntu
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin/.magisk/busybox"
export TERM=linux
export HOME=/root
export USER=root
export UID=0
export TMPDIR=/tmp
mount -o loop $PREFIX/img.ubuntu-armhf.root $PREFIX/ubuntu
mount -t proc proc $PREFIX/ubuntu/proc
mount -t sysfs sysfs $PREFIX/ubuntu/sys
mount --bind /dev $PREFIX/ubuntu/dev
mount -t devpts devpts $PREFIX/ubuntu/dev/pts

chroot $PREFIX/ubuntu /bin/bash -c "/debootstrap/debootstrap --second-stage"

cp $PREFIX/sources.list $PREFIX/ubuntu/etc/apt/sources.list

chroot $PREFIX/ubuntu /bin/bash -c "groupadd -g 3001 aid_bt"
chroot $PREFIX/ubuntu /bin/bash -c "groupadd -g 3002 aid_bt_net"
chroot $PREFIX/ubuntu /bin/bash -c "groupadd -g 3003 aid_inet"
chroot $PREFIX/ubuntu /bin/bash -c "groupadd -g 3004 aid_net_raw"
chroot $PREFIX/ubuntu /bin/bash -c "groupadd -g 3005 aid_admin"

chroot $PREFIX/ubuntu /bin/bash -c "usermod -a -G aid_inet root"

chroot $PREFIX/ubuntu /bin/bash -c "

dpkg-divert --local --rename --add /etc/init.d/udev
cp /etc/init.d/udev.distrib /etc/init.d/udev

sed -i 's/### END INIT INFO/exit 0/g' /etc/init.d/udev

dpkg-divert --local --rename --add /sbin/initctl
cp /bin/true /sbin/initctl

echo localhost > /etc/hostname
echo 'nameserver 8.8.8.8' >> /etc/resolv.conf

echo 'deb [arch=amd64,i386] http://us.archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse
deb [arch=amd64,i386] http://us.archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse
deb [arch=amd64,i386] http://us.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu bionic-security main restricted universe multiverse

deb [arch=arm64,armhf,ppc64el,s390x] http://ports.ubuntu.com/ubuntu-ports/ bionic main restricted universe multiverse
deb [arch=arm64,armhf,ppc64el,s390x] http://ports.ubuntu.com/ubuntu-ports/ bionic-updates main restricted universe multiverse
deb [arch=arm64,armhf,ppc64el,s390x] http://ports.ubuntu.com/ubuntu-ports/ bionic-backports main restricted universe multiverse
deb [arch=arm64,armhf,ppc64el,s390x] http://ports.ubuntu.com/ubuntu-ports/ bionic-security main restricted universe multiverse' >  /etc/apt/sources.list

export DEBIAN_FRONTEND=noninteractive

locale-gen en_US en_US.UTF-8
dpkg-reconfigure locales

usermod -g 3003 _apt

apt update
apt upgrade -y

apt install ubuntu-standard vim tmux openssh-client openssh-server -y

passwd -l root
adduser spaceswan
usermod -a -G sudo,aid_inet spaceswan
"
