#!/system/bin/sh
set -euo pipefail
termux-wake-lock
source /data/data/com.termux/files/home/.termux/boot/prefix.sh

while [ ! -d $PREFIX ]; do
  sleep 1
done

su -c "CMD='sudo /etc/init.d/ssh start' sh $PREFIX/enter_chroot"

if [ -f "/data/swapfile" ]; then
  su -c "swapon /data/swapfile"
fi

termux-wake-unlock
