#!/usr/bin/env python

import sys
import rospy
from kill_handling.broadcaster import KillBroadcaster

rospy.init_node('kill', anonymous=True)

id = sys.argv[1] if len(sys.argv) > 1 else rospy.get_name()
kill_br = KillBroadcaster(id=id, description='Command-line kill')
kill_br.send(True)
print 'Killed!'
rospy.spin()
try:
    kill_br.clear()
except rospy.service.ServiceException:
    pass  # This happens after rospy shutdown, but the server call goes through anyway
