#!/usr/bin/env python

import sys
import rospy
import rostopic
from kill_handling.broadcaster import KillBroadcaster
from kill_handling.listener import KillListener

rospy.init_node('kill', anonymous=True)

cond = rospy.get_param('~cond')

kill_br = KillBroadcaster(id=rospy.get_name(), description=rospy.get_name())
kill_listener = KillListener()

present = False


def got_msg(msg):
    global present, triggered
    present = eval(cond, globals(), dict((k, getattr(msg, k)) for k in dir(msg)))
rospy.Subscriber('topic', rostopic.get_topic_class(rospy.resolve_name('topic'), blocking=True)[0], got_msg)

triggered = False
while not rospy.is_shutdown():
    if present:
        triggered = True
    elif set(kill_listener.get_kills()) - set([rospy.get_name()]):
        # if there is another kill source
        triggered = False
    kill_br.send(triggered)
    rospy.sleep(rospy.Duration(0.1))
