#!/usr/bin/env python
import argparse

import nav_missions
from txros import util, NodeHandle
from twisted.internet import defer, reactor
from navigator_singleton.navigator import Navigator

from navigator_tools import fprint


@util.cancellableInlineCallbacks
def main():
    nh, args = yield NodeHandle.from_argv_with_remaining("navigator_mission_runner", anonymous=True)
    available_missions = [mission_name for mission_name in dir(nav_missions) if mission_name[0] != '_']

    parser = argparse.ArgumentParser(description='Mission Runner')
    parser.add_argument('missions', type=str, nargs='+',
                        help='Misison(s) from the navigator_missions folder to run.')
    parser.add_argument('-s', '--sim', action='store_true',
                        help='This will run navigator in sim mode (ie. not wait for odom or enu bounds). Don\'t do this on the boat.')
    args = parser.parse_args(args[1:])

    if "list" in args.missions:
        print "\nAvailable missions:\n   *",
        print '\n   * '.join(available_missions)
        print
        defer.returnValue(reactor.stop())

    n = yield Navigator(nh)._init(args.sim)

    for mission in args.missions:
        # Make sure all missions exist before we run
        assert mission in available_missions, "'{}' mission not found".format(mission)

    for mission in args.missions:
        to_run = getattr(nav_missions, mission)
        fprint("Running Mission!\n", title="MISSION")
        result = yield to_run.main(n)

        if result is None:
            fprint("{} finished with no result.", title="MISSION")
        else:
            fprint("{} finished with:", title="MISSION")
            print result

    defer.returnValue(reactor.stop())

if __name__ == '__main__':
    reactor.callWhenRunning(main)
    reactor.run()
