#!/bin/bash

ping_checker() {
	GREEN='\033[32m'
	RED='\033[31m'
	NC='\033[0m'
	HOST="$1"
	HOST_PING="$(ping -i 0.2 -w 2 -c 2 $HOST 2>&1 | grep '% packet' | awk -F'[%]' '{print $1}' | awk -F'[ ]' '{print $NF}')"
	if [ ! -z "$HOST_PING" ]; then
		if [ $HOST_PING -lt 25 ]; then
			echo -e "$HOST......${GREEN}OKAY${NC} "
		else
			echo -e "$HOST......${RED}NOT OKAY${NC}"
		fi
	else 
		echo -e "$HOST...... ${RED}NOT FOUND${NC}"
	fi
}
ping_checker mil-sub-gumstix.ad.mil.ufl.edu
ping_checker mil-com-teledyne-p900.ad.mil.ufl.edu
btrfs fi show
