# Defines one labeling project
---
datasets:
    - name: navigator_stc_seecam
      sources:
          # yamllint disable-line rule:line-length
          - file: stc.bag                       # bag file name. Will be resolved relative to bag dir set in yaml of cli argument
            # yamllint disable-line rule:line-length
            topic: /camera/seecam/image_raw     # Topic in bag to extract images from
            # yamllint disable-line rule:line-length
            encoding: rect_color                # How to process image if needed, can be mono, rect, color, or rect_color
            # yamllint disable-line rule:line-length
            freq: 0.5                           # Number of images to extract per second of bag time
          - file: stc_closer.bag
            topic: /camera/seecam/image_raw
            encoding: rect_color
            freq: 0.5
          - file: scanthecode.bag
            topic: /camera/seecam/image_raw
            encoding: rect_color
            freq: 0.05
          - file: stc2.bag
            topic: /camera/seecam/image_raw
            encoding: rect_color
            freq: 0.5
