#!/usr/bin/env python

import roslib
import rospy
from std_msgs.msg import Header
from mil_msgs.msg import Float64Stamped
roslib.load_manifest('depth_driver')


rospy.init_node('fake_depth')

pub = rospy.Publisher('/depth', Float64Stamped)

while not rospy.is_shutdown():
    pub.publish(Float64Stamped(
        header=Header(
            stamp=rospy.Time.now(),
            frame_id='/map',
        ),
        data=0,
    ))
    rospy.sleep(rospy.Duration(.2))
