steps:
  - name: "BUILDCONTAINERS"
    command: "MIL_DOCKER_TAG_ROOT=uf-mil-commit-${BUILDKITE_COMMIT} ./scripts/build_docker_containers"
  - wait
  - name: "BUILD"
    command: "./ci/run_ci"
    plugins:
      - docker#v3.3.0:
          image: uf-mil-commit-${BUILDKITE_COMMIT}:dev
          mount-buildkite-agent: false
          workdir: /home/mil-dev/catkin_ws/src/mil
          shell: ["/bin/bash", "-ic"]
