steps:
  - name: "BUILDCONTAINERS"
    command: "MIL_DOCKER_TAG_ROOT=uf-mil-commit-${BUILDKITE_COMMIT} ./scripts/build_docker_containers"
  - name: 'EXPERIMENT'
    command: "docker image ls"
  - name: "BUILD"
    command: "./ci/run_ci"
    plugins:
      - docker#v3.3.0:
          image: uf-mil-commit-${BUILDKITE_COMMIT}:ci-build
          mount-buildkite-agent: false
          workdir: /home/mil-ci/catkin_ws/src/mil
