#!/usr/bin/env python3
import sys

import rclpy
from mil_poi import POIServer

if __name__ == "__main__":
    rclpy.init(args=sys.argv)
    node = rclpy.create_node("poi_server")

    server = POIServer()
    rclpy.spin()
