#!/usr/bin/env python
import rospy
from ros_alarms import AlarmBroadcaster
import argparse

parser = argparse.ArgumentParser(description='Clears an alarm')
parser.add_argument("alarm_name", help='the name of the alarm to clear')
parser.add_argument("--parameters", nargs='+', default="",
                    help="parameters to pass to the alarm in the form of: \nparam1:=val1 param2:=val2")
args = parser.parse_args()

rospy.init_node("alarm_clear", anonymous=True)

# Parse parameters
split = [arg.split(":=") for arg in args.parameters]
params = {}
for name, value in split:
    try:
        params[name] = eval(value)
    except:
        params[name] = value

ab = AlarmBroadcaster(args.alarm_name)
ab.clear_alarm(parameters=params)
rospy.loginfo("Alarm cleared!")

