#!/usr/bin/env python
import rospy
from ros_alarms import AlarmBroadcaster
import argparse

parser = argparse.ArgumentParser(description='Clears an alarm')
parser.add_argument("alarm_name", help='the name of the alarm to clear')
# parser.add_argument("--parameters", nargs='+', default="",
#                     help="parameters to pass to the alarm in the form of: \nparam1:=val1, param2:=val2")
args = parser.parse_args()

rospy.init_node("alarm_raiser", anonymous=True)
ab = AlarmBroadcaster(args.alarm_name)
ab.clear_alarm()
rospy.loginfo("Alarm cleared!")

