#!/usr/bin/env python
import rospy
from ros_alarms import AlarmBroadcaster
import argparse

parser = argparse.ArgumentParser(description='Clears an alarm')
parser.add_argument("alarm_name", help='the name of the alarm to clear')
args = parser.parse_args()

rospy.init_node("alarm_clear", anonymous=True)
ab = AlarmBroadcaster(args.alarm_name)
ab.clear_alarm()
rospy.loginfo("Alarm cleared!")

