#!/usr/bin/env python
import rospy
from ros_alarms import AlarmBroadcaster
import argparse

parser = argparse.ArgumentParser(description='Raises an alarm')
parser.add_argument("alarm_name", help='the name of the alarm to raise')
parser.add_argument("--severity", type=int, default=5,
                    help="severity of the alarm, 1 being the heighest level")
parser.add_argument("--parameters", nargs='+', default="",
                    help="parameters to pass to the alarm in the form of: \nparam1:=val1 param2:=val2")
args = parser.parse_args()

rospy.init_node("alarm_raise", anonymous=True)
ab = AlarmBroadcaster(args.alarm_name)

# Parse parameters
split = [arg.split(":=") for arg in args.parameters]
params = {}
for name, value in split:
    try:
        params[name] = eval(value)
    except:
        params[name] = value

# Clip severity to be greater then 1
severity = 0 if args.severity < 0 else args.severity

ab.raise_alarm(parameters=params, severity=severity)
rospy.loginfo("Alarm raised!")

