#!/usr/bin/env python3

import math

import rospy
from geometry_msgs.msg import Vector3
from mil_msgs.msg import VelocityMeasurement, VelocityMeasurements
from std_msgs.msg import Header

rospy.init_node("fake_dvl")

pub = rospy.Publisher("dvl", VelocityMeasurements)

while not rospy.is_shutdown():
    rospy.sleep(0.1)

    pub.publish(
        VelocityMeasurements(
            header=Header(
                stamp=rospy.Time.now(),
                frame_id="/dvl",
            ),
            velocity_measurements=[
                VelocityMeasurement(
                    velocity=0,
                    correlation=0,
                    direction=Vector3(
                        *[
                            math.cos(i * 2 * math.pi / 4),
                            math.sin(i * 2 * math.pi / 4),
                            0,
                        ]
                    ),
                )
                for i in range(4)
            ],
        )
    )
