#!/usr/bin/python

from __future__ import division

import threading

import matplotlib.animation
import matplotlib.pyplot as plt

import util

gen = util.triggering(util.connect_to_samples(int(util.fs * .1)))
last_ping = gen.next()


def thread():
    global last_ping
    for ping in gen:
        last_ping = ping


threading.Thread(target=thread).start()

line = None


def redraw(frame):
    global line
    if last_ping is not None:
        if line is None:
            line = [ax.plot(x)[0] for x in last_ping]
        else:
            for i, x in enumerate(last_ping):
                line[i].set_ydata(x)


fig, ax = plt.subplots()
ani = matplotlib.animation.FuncAnimation(fig, redraw, interval=1)
plt.show()
