# Control and status register (CSR) types
uint8 TYPE_CONTROL=0
uint8 TYPE_ABSOLUTE=1
uint8 TYPE_FORMAT7=2
uint8 TYPE_ADVANCED_CONTROL=3
uint8 TYPE_PIO=4
uint8 TYPE_SIO=5
uint8 TYPE_STROBE=6
# Register type; defaults to 0.
uint8 type
# Register offset
uint64 offset
# Number of registers; 0 counts as 1; does not apply for single-value registers.
uint32 num_regs
# Mode for Format7 register, feature for absolute register; otherwise it does not apply.
uint32 mode
---
# Value of the register
uint32[] value
