# Control and status register (CSR) types
uint8 TYPE_CONTROL=0
uint8 TYPE_ABSOLUTE=1
uint8 TYPE_FORMAT7=2
uint8 TYPE_ADVANCED_CONTROL=3
uint8 TYPE_PIO=4
uint8 TYPE_SIO=5
uint8 TYPE_STROBE=6
# Register type; defaults to 0.
uint8 type
# Register offset
uint64 offset
# Value to set; call with an empty value succeed without any effect.
uint32[] value
# Mode for Format7 register, feature for absolute register; otherwise it does not apply.
uint32 mode
---
