#!/usr/bin/env python

from sub8 import tx_sub
import missions

print
print "Current missions:"
mission_list = [mission_name for mission_name in dir(missions) if not mission_name.startswith('_')]
print '  %s' % '\n  '.join(map(str, mission_list))
print