# Directory / filename of bag_name
# See examples below for what strings will produce what bags.
# bag_package_path is param set when running online bagger node
#  /home/example/2017/    -> /home/example/2017/2017-04-24-20:51:54.bag
#  camera_tests/test1.bag -> /bag_package_path/test1.bag
#  my_lidar_bag           -> /bag_package_path/my_lidar_bag.bag
#  sonar_tests/           -> /bag_package_path/sonar_tests/2017-04-24-20:51:54.bag
string bag_name

# Space seperated list of topics to bag. If empty string, all buffered topics will be bagged
string topics

# Time in seconds
float32 bag_time
---
string status
