#!/usr/bin/python

import numpy

import struct

import roslib
roslib.load_manifest('nv08c_driver')

import rospy
from std_msgs.msg import String, Header
from geometry_msgs.msg import Vector3

from rawgps_common import gps, glonass
from rawgps_common.msg import Measurements, Satellite

rospy.init_node('dump', anonymous=True)

class MyEphemeris(gps.Ephemeris):
    def __init__(self):
        pass

ephs = {}

antenna_pos = None

pub = rospy.Publisher('/gps', Measurements)
pub2 = rospy.Publisher('/gps_cp', Measurements)
last_carrier_phase = {}
def cb(msg):
    global antenna_pos
    if msg.data.startswith('\xf5'):
        msg = msg.data[1:]
        t_ms, week, gpsutc, glonassutc, timecorr = struct.unpack('<dHddb', msg[:27])
        t = t_ms/1000 + gpsutc/1000
        glonass_t = t_ms/1000 + glonassutc/1000
        print 'RAW', t_ms/1000, week, gpsutc/1000, glonassutc/1000, timecorr/1000
        assert len(msg[27:]) % 30 == 0
        m = Measurements(
            header=Header(
                stamp=rospy.Time.now(),
                frame_id='/gps',
            ),
            satellites=[],
        )
        m2 = Measurements(
            header=Header(
                stamp=rospy.Time.now(),
                frame_id='/gps',
            ),
            satellites=[],
        )
        for i in xrange(len(msg[27:]) // 30):
            d = msg[27+30*i:27+30*i+30]
            sig_type, sat_num, carrier_num, snr, carrier_phase, pseudo_range, doppler_freq, flags, res = struct.unpack('<BBbBdddBB', d)
            assert flags & 0x01
            doppler_freq_good = 'G' if flags & 0x02 else 'g'
            carrier_phase_good = 'G' if flags & 0x08 else 'g'
            carrier_phase_good += 'F' if not flags & 0x20 else 'f'
            pseudorange_good = 'G' if flags & 0x02 else 'g'
            pseudorange_good += 'F' if flags & 0x10 else 'f'
            pseudorange_good += 'S' if flags & 0x04 else 's'
            print '    %3i %3i %3i %3i %20.9f:%s %15.10f:%s %15.7f:%s %3i %3i' % (sig_type, sat_num, carrier_num, snr, carrier_phase, carrier_phase_good, pseudo_range, pseudorange_good, doppler_freq, doppler_freq_good, flags, res)
            
            if sig_type == 0x02:
                if antenna_pos is not None and ('gps', sat_num) in ephs:
                    eph = ephs[('gps', sat_num)]
                    sat_pos, sat_3vel = eph.predict(t)
                    sat_dir = sat_pos - antenna_pos;sat_dir /= numpy.linalg.norm(sat_dir)
                    sat_vel = -sat_3vel.dot(sat_dir)
                    if flags & 0x02:
                        measured_vel = doppler_freq*gps.c/gps.L1_f0
                        m.satellites.append(Satellite(
                            direction_enu=Vector3(*gps.enu_from_ecef(sat_dir, antenna_pos)),
                            velocity_plus_drift=measured_vel - sat_vel,
                            prn=sat_num,
                            cn0=snr,
                        ))
                    #print ' '*7, carrier_phase*gps.c/gps.L1_f0 + numpy.linalg.norm(antenna_pos-eph.predict(t))
                    if sat_num in last_carrier_phase and flags & 0x08:
                        a, b = last_carrier_phase[sat_num]
                        #print '       d/dt', -(carrier_phase-a)/(t-b)*gps.c/gps.L1_f0 - sat_vel#, measured_vel - sat_vel
                        m2.satellites.append(Satellite(
                            direction_enu=Vector3(*gps.enu_from_ecef(sat_dir, antenna_pos)),
                            velocity_plus_drift=-(carrier_phase-a)/(t-b)*gps.c/gps.L1_f0 - sat_vel,
                            prn=sat_num,
                            cn0=snr,
                        ))
                last_carrier_phase[sat_num] = carrier_phase, t
                if not (flags & 0x08):
                    last_carrier_phase.pop(sat_num, None)
            elif sig_type == 0x01:
                if antenna_pos is not None and ('glonass', sat_num, carrier_num) in ephs:
                    eph = ephs[('glonass', sat_num, carrier_num)]
                    if flags & 0x02:
                        measured_vel = doppler_freq*gps.c/glonass.L1_f0
                        #print ' '*7, sat_vel, measured_vel
                        sat_pos, sat_3vel = eph.predict(glonass_t)
                        sat_dir = sat_pos - antenna_pos;sat_dir /= numpy.linalg.norm(sat_dir)
                        sat_vel = -sat_3vel.dot(sat_dir)
                        '''m.satellites.append(Satellite(
                            direction_enu=Vector3(*gps.enu_from_ecef(sat_dir, antenna_pos)),
                            velocity_plus_drift=measured_vel - sat_vel,
                            prn=1000000 + 1000*sat_num + carrier_num,
                            cn0=-snr,
                        ))'''
                        #print carrier_num, measured_vel - sat_vel
                        #print 'added', 1000000 + 1000*sat_num + carrier_num
        #print
        pub.publish(m)
        pub2.publish(m2)
    elif msg.data.startswith('\x88'):
        lat, lon, alt, err, t, week, lat_vel, lon_vel, alt_vel, dev, status = struct.unpack('<dddf10shdddfB', msg.data[1:])
        #print 'PVT', lat, lon, alt, err, None, week, lat_vel, lon_vel, alt_vel, dev, status
    elif msg.data.startswith('\xf6'):
        x, y, z, x_err, y_err, z_err, flags = struct.unpack('<ddddddB', msg.data[1:])
        #print 'GCA', x, y, z, x_err, y_err, z_err, flags
        antenna_pos = numpy.array([x, y, z])
    elif msg.data.startswith('\x70'):
        channels, description, serial, res1, res2, res3, res4 = struct.unpack('<B21sI21sI21sI', msg.data[1:])
        #print 'VER', channels, description, serial, res1, res2, res3, res4
    elif msg.data.startswith('\x4a'):
        a0, a1, a2, a3, b0, b1, b2, b3, reliable = struct.unpack('<ffffffffB', msg.data[1:])
        #print 'ION', a0, a1, a2, a3, b0, b1, b2, b3, reliable
    elif msg.data.startswith('\x4b'):
        A1, A0, t_ot, WN_t, dt_LS, WN_LSF, DN, dt_LSF, reliable, NA, tau_C, glonass_reliable = struct.unpack('<ddIHhHHhBHdB', msg.data[1:])
        print 'TSP', A1, A0, t_ot, WN_t, dt_LS, WN_LSF, DN, dt_LSF, reliable, NA, tau_C, glonass_reliable
    elif msg.data.startswith('\xe7'):
        (data_type,), value = struct.unpack('<B', msg.data[1]), msg.data[2:]
        #print 'AOP', data_type, value.encode('hex')
    elif msg.data.startswith('\xf7'):
        sat_type, sat_num = struct.unpack('<BB', msg.data[1:3])
        if sat_type == 1: # GPS
            Crs, Dn, M0, Cuc, E, Cus, SqrtA, Toe, Cic, Omega0, Cis, I0, Crc, W, OmegaR, Ir, Tgd, Toc, Af2, Af1, Af0, URA, IODE, IODC, CodeL2, L2_Pdata_flag, WeekN = struct.unpack('<ffdfdfddfdfdfdddfdfffHHHHHH', msg.data[3:])
            #print 'EPH', sat_num, Crs, Dn, M0, Cuc, E, Cus, SqrtA, Toe, Cic, Omega0, Cis, I0, Crc, W, OmegaR, Ir, Tgd, Toc, Af2, Af1, Af0, URA, IODE, IODC, CodeL2, L2_Pdata_flag, WeekN
            eph = MyEphemeris()
            eph.C_rs, eph.delta_n, eph.M_0, eph.C_uc, eph.e, eph.C_us, eph.sqrt_A, eph.t_oe, eph.C_ic, eph.omega_0, eph.C_is, eph.i_0, eph.C_rc, eph.omega, eph.omega_dot, eph.IDOT, eph.t_gd, eph.t_oc, eph.a_f2, eph.a_f1, eph.a_f0, eph.URA, eph.IODE, eph.IODC = Crs, Dn*1000, M0, Cuc, E, Cus, SqrtA, Toe/1000, Cic, Omega0, Cis, I0, Crc, W, OmegaR*1000, Ir*1000, Tgd/1000, Toc/1000, Af2*1000, Af1, Af0/1000, URA, IODE, IODC
            print sat_num, eph
            #print eph.predict(0)
            ephs[('gps', sat_num)] = eph
        elif sat_type == 2: # GLONASS
            carrier, X, Y, Z, Vx, Vy, Vz, Ax, Ay, Az, t_b, gamma_n, tau_n, E_n = struct.unpack('<bddddddddddffH', msg.data[3:])
            eph = glonass.Ephemeris(t_b/1e3, X, Y, Z, Vx*1e3, Vy*1e3, Vz*1e3, Ax*1e6, Ay*1e6, Az*1e6, gamma_n, tau_n*1e3)
            #print eph.predict(0)
            ephs[('glonass', sat_num, carrier)] = eph
            print 'GPH', eph
        else:
            print 'unknown sat_type', sat_type
    else:
        print msg.data.encode('hex'), len(msg.data)
rospy.Subscriber('/gps_serial', String, cb)

rospy.spin()
