# goal. copies PoseTwistStamped.
Header header
mil_msgs/PoseTwist posetwist
float64 speed
bool uncoordinated # false goes in a straight line, true achieves some components before others
bool blind # true ignores waypoint validation, false will check for collisions
float64 linear_tolerance # distance from goal for result to be sent
float64 angular_tolerance
---
# result
string error # Returns waypoint error
bool success # true if successfully went to assigned waypoint
---
# feedback
