#!/usr/bin/env python
import rospy
from actionlib import TerminalState
import argparse
from mil_tasks_core import TaskClient
import json


class TaskClientCli(object):
    '''
    Node to send and monitor a new task, cancel a task, or cancel the current
    tasks. Verbosely prints current state and fedback to the terminal.
    '''
    def __init__(self):
        self.client = TaskClient()
        connected = self.client.wait_for_server(rospy.Duration(0.25))
        if not connected:  # If it didn't connect quickly, print and wait forever
            print 'Waiting on action server at ', self.client.NS
            self.client.wait_for_server()
        self.running = False  # Tracks if we are currently waiting for a task to finish
        rospy.on_shutdown(self.on_shutdown)

    @classmethod
    def list(cls):
        tasks = TaskClient.available_tasks()
        if not tasks:
            print '{} param not set. Is task runner running?'.format(cls.LIST_PARAM)
            return
        print 'Available Tasks:'
        for task in tasks:
            print '- ', task

    def cancel_all(self):
        self.client.cancel_all_goals()

    def _feedback_cb(self, msg):
        if self.first_feedback:
            self.first_feedback = False
            print 'Feedback:'
        print '- ', msg.message

    def on_shutdown(self):
        '''
        If shutdown (rosnode kill, Control+C, etc),
        cancel the current goal if we sent one.
        '''
        if self.running:
            print 'Cancelling goal'
            self.cancel_all()

    def run_task(self, task, parameters):
        self.first_feedback = True
        print 'Starting task ', task
        self.running = True
        self.client.run_task(task, parameters, feedback_cb=self._feedback_cb)
        self.client.wait_for_result()
        result = self.client.get_result()
        self.running = False
        if result is None:
            return
        state = self.client.get_state()
        if state != TerminalState.SUCCEEDED:
            print 'Goal finished with state ', TerminalState.to_string(state)
        print 'Goal successful' if result.success else 'Goal unsuccessful'
        if result.result != '':
            print "Result: '{}'".format(result.result)
        if len(result.parameters) > 0:
            try:
                x = json.loads(result.parameters)
                if not isinstance(x, dict):
                    raise ValueError('not dict')
                for key, value in x.iteritems():
                    print '{}: {}'.format(key, value)
            except ValueError:
                print 'could not decode result parameters'


def main():
    argv = rospy.myargv()
    parser = argparse.ArgumentParser(description='Runs a task on the task_runner server')
    subparser = parser.add_subparsers()

    list_parser = subparser.add_parser('list', help='List available tasks')
    list_parser.set_defaults(cmd='list')

    cancel_parser = subparser.add_parser('cancel', help='Cancel current task')
    cancel_parser.set_defaults(cmd='cancel')

    run_parser = subparser.add_parser('run', help='Start a new task')
    run_parser.set_defaults(cmd='run')
    run_parser.add_argument('task', help='name of task to run')
    run_parser.add_argument('parameters', nargs=argparse.REMAINDER, help='list of parameters to pass to task.\
                                                       Will be concatenated into one string')
    args = parser.parse_args(argv[1:])

    if args.cmd == 'list':
        TaskClientCli.list()
        return
    rospy.init_node('task_client', anonymous=True)
    client = TaskClientCli()
    if args.cmd == 'cancel':
        client.cancel_all()
        print 'All goals canceled'
        return
    assert args.cmd == 'run'
    parameters = ' '.join(args.parameters)
    client.run_task(args.task, parameters)

if __name__ == '__main__':
    main()
