#!/bin/bash
usage="$(basename "$0") [-h | --help] [-s | --scratch] [-n | --no-source]
[-d | --doxygen] -- build MIL docs

where:
    -h  show this help text
    -n  avoid building reference docs; this is useful for mechanical and electrical
        members who may not have ROS setup
    -s  build the docs from scratch (don't use cache)
    -d  build doxygen documentation cache"

# Get root directory of MIL repo
MIL_DIR="$(realpath "$(dirname "${BASH_SOURCE[@]}")/..")"

# Directory to build docs into
BUILD_DIR=$HOME/.mil/docs
mkdir -p "$BUILD_DIR"/doctrees
mkdir -p "$BUILD_DIR"/html

DOXYGEN=false
SCRATCH=false
NO_SOURCE=false

while [[ $# -gt 0 ]]; do
  case $1 in
    -d|--doxygen)
      DOXYGEN=true
      shift # past argument
      ;;
    -s|--scratch)
      SCRATCH=true
      shift # past argument
      ;;
    -n|--no-source)
      NO_SOURCE=true
      shift # past argument
      ;;
    -h|--help)
      echo "$usage"
      exit
      shift # past argument
      ;;
    -*)
      echo "Unknown option $1"
      exit 1
      ;;
  esac
done

if [ "$DOXYGEN" = true ]; then
    #Doxygen
    cd "$HOME"/.mil || echo "Could not find .mil output folder: Use mkdir ~/.mil to create!"
    doxygen "$MIL_DIR"/docs/Doxyfile
    cd - || exit 1
fi

if [ "$SCRATCH" = true ]; then
    #Doxygen
    NO_SOURCE="$NO_SOURCE" sphinx-build -E -b html -d "$BUILD_DIR"/doctrees "$MIL_DIR"/docs "$BUILD_DIR"/html
else
    NO_SOURCE="$NO_SOURCE" sphinx-build -b html -d "$BUILD_DIR"/doctrees "$MIL_DIR"/docs "$BUILD_DIR"/html
fi

# Then Sphinx build
echo "Docs available at file://$BUILD_DIR/html/index.html"
