#!/bin/bash
set -euo pipefail

# Usage
if [ $# -gt 0 ]
then
    echo "Usage: $0"
    exit 1
fi

if [[ $EUID -ne 0 ]] && [[ $(id -Gn "$USER" | grep -c "docker") == 0 ]] ; then
  echo "You need docker access to run this script."
  echo "Add yourself to the docker group to run this script."
  exit 1
fi

# Allow the tag name to have prefix, used by CI
MIL_DOCKER_TAG_ROOT=${MIL_DOCKER_TAG_ROOT:-"uf-mil"}

# Quite mode so will only output if something goes wrong
DOCKER_ARGS=""

# Cache path in repo where dockerfiles are
DOCKER_BASE_PATH="$(realpath $(dirname $BASH_SOURCE)/../docker)"

build_mil_docker_image()
{
  docker build $DOCKER_ARGS $DOCKER_BASE_PATH/$1 -t $MIL_DOCKER_TAG_ROOT:$1 --build-arg MIL_DOCKER_TAG_ROOT=${MIL_DOCKER_TAG_ROOT}
}

# Build each of the images
build_mil_docker_image base
build_mil_docker_image dev
build_mil_docker_image ci-server

USER=$(whoami)

# If dev container has not been compiled before
if [ ! -f $HOME/.mil/dev-docker-ws/devel/setup.sh ] && [ $USER != "root" ]; then
    # Create Space to save build and devel space for dev container
    mkdir -p $HOME/.mil/dev-docker-ws
    chown $UID:1000 -R $HOME/.mil/dev-docker-ws
    mkdir -p $HOME/.mil/dev-docker-ws/build
    mkdir -p $HOME/.mil/dev-docker-ws/devel

    # Run the Dev container once and compile
    docker run -t \
        --rm \
        -v $(realpath $(dirname $BASH_SOURCE)/../):/home/mil-dev/catkin_ws/src/mil/ \
        -v $HOME/.mil/dev-docker-ws/build:/home/mil-dev/catkin_ws/build/ \
        -v $HOME/.mil/dev-docker-ws/devel:/home/mil-dev/catkin_ws/devel/ \
        --name dev-$USER-$UID \
        uf-mil:dev \
        /bin/bash -c "source /opt/ros/melodic/setup.bash && \
                      catkin_make -C /home/mil-dev/catkin_ws -j8"
fi

