#!/bin/bash
# This script is run by the navigator user when the main NaviGator computer starts.
USER="navigator"
SDGPS_DIR="/home/$USER/sdgps/sdgps_current"
SDGPS="$SDGPS_DIR/build/main"
ANTENNA_POSITION="[0.37465,-0.136525,0.587502]"
CMD="(cd $SDGPS_DIR;sudo $SDGPS sylphase-usbgpsimu2 --antenna-position '$ANTENNA_POSITION' ! tracker ! kf2 --decimation 10 ! listen-solution-tcp 1234)"
ROSCORE="roscore"
SESSION="sdgps"
TMUX="tmux"
if $TMUX has-session -t $SESSION 2> /dev/null; then
    echo "$SESSION already created, aborting"
    exit 0
fi
$TMUX new-session -d -s ${SESSION} -n "roscore"
$TMUX send-keys -t $SESSION "$ROSCORE" C-m
$TMUX new-window -t $SESSION -n "sdgps"
$TMUX send-keys -t $SESSION "$CMD" C-m


