#!/bin/bash
set -euo pipefail

usage()
{
    echo "Usage: $0 [OPTION]"


    echo "OPTIONS:

        --help -h

            Display this page.

        --dev-server

            This flag causes the correct export of ros environment variables to the container when running remotely. Only to be used when runnning the container on the dev server."

exit 1
}

ROS_ENV=""
NAME=""


if [[ $* == *--dev-server* ]]; then
    ROS_PORT=${UID}0
    CONTAINER_IP=`hostname -I`
    CONTAINER_IP=`echo $CONTAINER_IP | head -n1 | awk '{print $1;}'`
    ROS_ENV="\
      --env ROS_MASTER_URI=http://localhost:$ROS_PORT \
      --env ROS_HOSTNAME=$CONTAINER_IP \
      --env ROS_PORT=$ROS_PORT"
    NAME="--name dev-$USER-$UID"

elif
    [[ $* == *--help* ]] || [[ $* == *-h* ]]; then
    usage
fi

VIM_CONFIG=""
if [ -f $HOME/.vimrc ]; then
    VIM_CONFIG="-v $HOME/.vimrc:/home/mil-dev/.vimrc"
fi

docker run -it \
    -v $(realpath $(dirname $BASH_SOURCE)/../):/home/mil-dev/catkin_ws/src/mil/ \
    -v $HOME/.mil/dev-docker-ws/build:/home/mil-dev/catkin_ws/build/ \
    -v $HOME/.mil/dev-docker-ws/devel:/home/mil-dev/catkin_ws/devel/ \
    $VIM_CONFIG \
    --net host \
    $ROS_ENV \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    $NAME \
    --rm \
    uf-mil:dev
