#!/bin/bash
set -euo pipefail

usage()
{
  echo "Usage: <branch>"
  exit 1
}

[[ $# -ne 1 ]] && usage
BRANCH=$1

sudo docker run -it \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --env ROS_MASTER_URI=http://localhost:11311 \
    --env ROS_HOSTNAME=localhost \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    --network=host \
    uf-mil:vrx-trial-${BRANCH}
