#!/bin/bash
# Run when VRX container is started
set -euo pipefail

# Source bashrc to get ROS/catkin environment
set +u
. /opt/ros/melodic/setup.bash
. $HOME/catkin_ws/devel/setup.bash
set -u


sudo rosdep init
rosdep update

# Launch vrx_master to complete vrx task
echo "Running UF VRX Code"
roslaunch navigator_launch vrx_master.launch run_task:=True --screen
