---
!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  frame: ecef
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      frame: ecef
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
      x1: 743766.0
      x2: 743767.0
      x3: 743864.0
      x4: 743833.0
      y1: -5503838.0
      y2: -5503862.0
      y3: -5503866.0
      y4: -5503820.0
      z1: 3125639.0
      z2: 3125575.0
      z3: 3125608.0
      z4: 3125659.0
    state: []
  x1: 743766.0
  x2: 743767.0
  x3: 743864.0
  x4: 743833.0
  y1: -5503838.0
  y2: -5503862.0
  y3: -5503866.0
  y4: -5503820.0
  z1: 3125639.0
  z2: 3125575.0
  z3: 3125608.0
  z4: 3125659.0
state: []
