#!/bin/bash

SESSION=thruster_monitoring
TMUX="/usr/bin/tmux -L diagnostics"

# Don't do anything if session already exists
if $TMUX has-session -t $SESSION &> /dev/null; then
	echo "Thruster monitoring session was already started. Aborting."
	exit 0
else
	echo "Starting thruster monitoring session on socket /tmp/tmux-1000/diagnostics."
fi

# Create thruster monitoring session
$TMUX new-session -d -s $SESSION
$TMUX rename-window status

# Make bottom section with 3 splits
$TMUX split-window -v
$TMUX split-window -h 
$TMUX select-pane -L
$TMUX split-window -h
$TMUX split-window -h
$TMUX select-pane -L
$TMUX select-pane -L
$TMUX split-window -h

# Split top pane into 8 equally sized ones
$TMUX select-pane -U
$TMUX split-window -h
$TMUX split-window -h
$TMUX split-window -h
$TMUX select-pane -L
$TMUX select-pane -L
$TMUX split-window -h
$TMUX select-pane -L
$TMUX select-pane -L
$TMUX split-window -h
$TMUX split-window -h
$TMUX select-pane -L
$TMUX select-pane -L
$TMUX split-window -h

# Run all of the topic monitoring commands
$TMUX select-pane -t top-left
$TMUX send-keys "rostopic echo /thrusters/status/FLH" C-m
$TMUX select-pane -R
$TMUX send-keys "rostopic echo /thrusters/status/FRH" C-m
$TMUX select-pane -R
$TMUX send-keys "rostopic echo /thrusters/status/BLH" C-m
$TMUX select-pane -R
$TMUX send-keys "rostopic echo /thrusters/status/BRH" C-m
$TMUX select-pane -R
$TMUX send-keys "rostopic echo /thrusters/status/FLV" C-m
$TMUX select-pane -R
$TMUX send-keys "rostopic echo /thrusters/status/FRV" C-m
$TMUX select-pane -R
$TMUX send-keys "rostopic echo /thrusters/status/BLV" C-m
$TMUX select-pane -R
$TMUX send-keys "rostopic echo /thrusters/status/BRV" C-m
$TMUX select-pane -t bottom-left
$TMUX send-keys "rostopic echo /thrusters/thrust" C-m
$TMUX select-pane -R
$TMUX send-keys "rostopic echo /wrench" C-m
$TMUX select-pane -R
$TMUX send-keys "rostopic echo /wrench_error" C-m
$TMUX select-pane -R
$TMUX send-keys "rostopic echo /bus_voltage" C-m
$TMUX split-window -v -p50
$TMUX send-keys "amonitor kill" C-m
