#!/usr/bin/env python

from __future__ import division

import sys

import roslib
roslib.load_manifest('skytraq_driver')
import rosbag
from std_msgs.msg import Header, String
from skytraq_driver.msg import SerialPacket


with rosbag.Bag(sys.argv[1]) as bag:
    with rosbag.Bag(sys.argv[2], 'w') as bag2:
        for topic, msg, t in bag.read_messages():
            if topic == sys.argv[3]:
                bag2.write(sys.argv[4], SerialPacket(
                    header=Header(
                        stamp=t,
                    ),
                    payload=msg.data,
                ), t)
            else:
                bag2.write(topic, msg, t)
