#!/usr/bin/env python

from __future__ import division

import random
import sys

import numpy
import scipy.linalg
import yaml

import roslib
roslib.load_manifest('skytraq_driver')
import rosbag
from skytraq_driver.msg import Measurement, Measurements, Satellite


m = {}
with rosbag.Bag(sys.argv[1]) as bag:
    for topic, msg, t in bag.read_messages():
        if topic == sys.argv[3]:
            m.setdefault(msg.header.stamp, Measurements(header=msg.header)).satellites.append(Satellite(
                direction_enu=msg.direction_enu,
                velocity_plus_drift=msg.velocity_plus_drift,
                prn=msg.prn,
                cn0=msg.cn0,
            ))

with rosbag.Bag(sys.argv[1]) as bag:
    with rosbag.Bag(sys.argv[2], 'w') as bag2:
        for topic, msg, t in bag.read_messages():
            if topic == sys.argv[3]:
                if msg.header.stamp in m:
                    bag2.write(sys.argv[4], m.pop(msg.header.stamp), t)
            else:
                bag2.write(topic, msg, t)
