# list an arbitrary set of topics to  subscribe to and stream:
# overwrite default stream time on specific topics in this config

---
stream_time: 60  # seconds

# potential parameters

# yamllint disable-line rule:line-length
# determines how frequently unavailable topics are resubscribed to defaults to 3.0 seconds:
# resubscribe_period : 3.0 # seconds

# yamllint disable-line rule:line-length
# adds additional topics to stream, or overrides default stream time on specific topics, leave blank
# to bag MIL bag script environmental variables only
# topics : [["/odom", 20], ["/absodom", 20]]

# sets bag package path, default to home/user/bags/current-date
# bag_package_path : "home/sub8/mil_ws/bags"

# Bool parameter that determines if current date is appended to bag directory
# for example defaults to: "home/user/bags/current-date" when True
# else bag directory goes to: "home/user/bags when False
dated_folder: true
