#!/usr/bin/env python3
# See argparse description
import socket
import time
import argparse

parser = argparse.ArgumentParser(
    description='Creates a TCP server and send any client whom connects the full contents of the specified binary file')
parser.add_argument('file', help='name of file to playback')
parser.add_argument('--port', default=10001, type=int, help='Port to bind to')
parser.add_argument('--ip', default='127.0.0.1', help='IP addres to bind to')
args = parser.parse_args()

TCP_IP = args.ip
TCP_PORT = args.port

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind((TCP_IP, TCP_PORT))
s.listen(1)

FILE = args.file
data = bytes(open(FILE, 'rb').read())

while True:
    conn, addr = s.accept()
    print('New connection')
    conn.send(data)
    conn.close()
    print('Clossed connection')
