#!/usr/bin/env python3
from threading import Lock
from typing import List

import numpy as np
import rospy
from dynamic_reconfigure.msg import Config
from dynamic_reconfigure.server import Server as DynamicReconfigureServer
from geometry_msgs.msg import WrenchStamped
from mil_msgs.msg import PoseTwistStamped
from mil_tools import (
    numpy_to_wrench,
    odometry_to_numpy,
    pose_to_numpy,
    quat_to_rotvec,
    quaternion_matrix,
    twist_to_numpy,
)
from nav_msgs.msg import Odometry
from ros_alarms import AlarmListener
from subjugator_controller.cfg import AdaptiveControllerConfig
from tf.transformations import quaternion_inverse, quaternion_multiply


class Sub8AdapativeController:
    def __init__(self):
        """
        Sub8 adaptive controller receives desired state from a
        trajectory generator, and uses the current state of the
        sub (feeedback) to calculate the control input to achieve
        the desired state.

        This is achieved by using a PID controller and other adaptive
        gains.
        Comment: dist == disturbance, est == estimate

        Attributes:
            kp (np.array): proportional gain
            kd (np.array): derivative gain
            ki (np.array): i gain applied to the integral of the twist error
            kg (np.array): g gain applied to the integral of the pose error
            use_learned (bool): whether to use learned disturbances
            last_config (Config): last config sent to reconfigure
            desired_position (np.array): desired position
            desired_orientation (np.array): desired orientation
            desired_twist_world (np.array): desired twist in world frame
            position (np.array): current position
            orientation (np.array): current orientation
            twist_body (np.array): current twist in body frame
            twist_world (np.array): current twist in world frame
            body_to_world (np.array): body to world transformation matrix
            world_to_body (np.array): world to body transformation matrix
            dist_est_world (np.array): disturbance estimate in world frame
            drag_est_body (np.array): drag estimate in body frame
            learning_distance (float): maximum distance of error to learn
            body_frame (str): body frame id
            global_frame (str): global frame id
        """
        self.lock = Lock()
        np.set_printoptions(precision=2)

        # Initialize gains and setup dynamic reconfigure
        self.kp = np.zeros(6).T
        self.kd = np.zeros(6).T
        self.ki = np.zeros(6).T
        self.kg = np.zeros(6).T
        self.learning_distance = (
            1.0  # TODO: investigate how to tune this for better performance
        )
        self.use_learned = False
        self.last_config = None
        self.reconfigure_server = DynamicReconfigureServer(
            AdaptiveControllerConfig,
            self.reconfigure,
        )

        # Initialize state variables
        self.dist_est_world = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0]).T
        self.drag_est_body = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0]).T
        self.body_frame = None
        self.global_frame = None
        self.last_update = None
        self.desired_position = None
        self.desired_orientation = None
        self.desired_twist_world = None
        self.body_to_world = None
        self.world_to_body = None
        self.position = None
        self.orientation = None
        self.twist_world = None
        self.pose = None
        self.twist_world = None
        self.twist_body = None
        self.debug = rospy.get_param("~debug", False)

        self.kill_listener = AlarmListener("kill")
        self.wrench_pub = rospy.Publisher("/wrench", WrenchStamped, queue_size=3)
        if self.debug:
            self.adaptation_wrench_pub = rospy.Publisher(
                "~adaptation",
                WrenchStamped,
                queue_size=1,
            )
            self.dist_wrench_pub = rospy.Publisher("~dist", WrenchStamped, queue_size=1)
            self.drag_wrench_pub = rospy.Publisher("~drag", WrenchStamped, queue_size=1)
            self.pose_error_pub = rospy.Publisher(
                "~pose_error",
                WrenchStamped,
                queue_size=1,
            )
            self.twist_error_pub = rospy.Publisher(
                "~twist_error",
                WrenchStamped,
                queue_size=1,
            )
        self.odom_sub = rospy.Subscriber("/odom", Odometry, self.odom_cb, queue_size=3)
        self.ref = rospy.Subscriber(
            "/trajectory",
            PoseTwistStamped,
            self.trajectory_cb,
            queue_size=3,
        )

    @staticmethod
    def parse_gains(gains) -> List[float]:
        ret = [float(gain.strip()) for gain in gains.split(",")]
        if len(ret) != 6:
            raise ValueError("not 6")
        return ret

    def reconfigure(self, config: Config, level: int) -> Config:
        """Dynamic reconfigure callback. This allows for gains
        to be tuned interactively.
        References: http://wiki.ros.org/dynamic_reconfigure
        """
        try:
            kp = self.parse_gains(config["kp"])
            kd = self.parse_gains(config["kd"])
            ki = self.parse_gains(config["ki"])
            kg = self.parse_gains(config["kg"])
        except ValueError as e:
            rospy.logwarn(f"Invalid dynamic reconfigure: {e}")
            return self.last_config
        self.kp = np.array(kp)
        self.kd = np.array(kd)
        self.ki = np.array(ki)
        self.kg = np.array(kg)
        self.use_learned = config["use_learned"]
        self.last_config = config
        rospy.loginfo("Gains successfully updated via dynamic reconfigure")
        return config

    def update(self) -> None:
        """Computes the pose and twist errors, updates the regressors (estimates),
        and calculates and publishes the desired wrench to be applied based on the
        PD gains, the estimated drag in the body frame and the estimated disturbances
        in the world frame.
        """
        now = rospy.Time.now()
        kill_alarm = self.kill_listener.get_alarm(fetch=False)

        # Send a zeroed wrench if killed, missing odometry, or missing goal
        if (
            self.desired_position is None
            or self.position is None
            or kill_alarm is None
            or kill_alarm.raised
        ):
            zero_wrench = np.zeros(6, dtype=float)
            self.wrench_pub.publish(
                self.make_wrench_msg(zero_wrench, frame_id=self.body_frame, stamp=now),
            )
            return

        # Calculate error in position, orientation, and twist
        position_error_world = self.desired_position - self.position
        orientation_error_world = quat_to_rotvec(
            quaternion_multiply(
                self.desired_orientation,
                quaternion_inverse(self.orientation),
            ),
        )
        pose_error_world = np.concatenate(
            (position_error_world, orientation_error_world),
        )
        twist_error_world = self.desired_twist_world - self.twist_world
        twist_error_body = self.world_to_body.dot(twist_error_world)

        # Rotate gains into world frame
        kp = self.body_to_world.dot(np.diag(self.kp)).dot(self.world_to_body)
        kd = self.body_to_world.dot(np.diag(self.kd)).dot(self.world_to_body)

        # Calculate part of wrench from feedback
        feedback_proportional_world = kp.dot(pose_error_world)
        feedback_derivative_world = kd.dot(twist_error_world)
        feedback_world = feedback_proportional_world + feedback_derivative_world

        # Calculate part of wrench from learned parameters
        drag_effort_body = np.multiply(self.drag_est_body, self.twist_body)
        drag_effort_world = self.body_to_world.dot(drag_effort_body)
        wrench_adaptation_world = drag_effort_world + self.dist_est_world

        if self.use_learned:
            # If learning is on, total wrench is feedback + learned integrator
            wrench_world = wrench_adaptation_world + feedback_world
        else:
            # if learning is off, wrench is just from feedback
            wrench_world = feedback_world

        # Convert wrench to body frame as per ROS convention
        wrench_body = self.world_to_body.dot(wrench_world)

        # Publish wrench
        self.wrench_pub.publish(
            self.make_wrench_msg(wrench_body, frame_id=self.body_frame, stamp=now),
        )

        # Update regressors
        dist = np.linalg.norm(pose_error_world)
        if (
            self.last_update is not None
            and dist < self.learning_distance
            and self.use_learned
        ):
            dt = (now - self.last_update).to_sec()
            self.drag_est_body = (
                self.drag_est_body + np.multiply(self.ki, twist_error_body) * dt
            )
            self.dist_est_world = (
                self.dist_est_world + np.multiply(self.kg, pose_error_world) * dt
            )
            # print 'Drag est', self.drag_est_body
            # print 'Dist est', self.dist_est_world
        self.last_update = now

        if self.debug:
            # Publish wrench showing only adaptation terms
            adapation_wrench_body = self.world_to_body.dot(wrench_adaptation_world)
            self.adaptation_wrench_pub.publish(
                self.make_wrench_msg(
                    adapation_wrench_body,
                    frame_id=self.body_frame,
                    stamp=now,
                ),
            )
            self.dist_wrench_pub.publish(
                self.make_wrench_msg(
                    self.dist_est_world,
                    frame_id=self.global_frame,
                    stamp=now,
                ),
            )
            self.drag_wrench_pub.publish(
                self.make_wrench_msg(
                    drag_effort_body,
                    frame_id=self.body_frame,
                    stamp=now,
                ),
            )
            self.pose_error_pub.publish(
                self.make_wrench_msg(
                    pose_error_world,
                    frame_id=self.global_frame,
                    stamp=now,
                ),
            )
            self.twist_error_pub.publish(
                self.make_wrench_msg(
                    twist_error_body,
                    frame_id=self.body_frame,
                    stamp=now,
                ),
            )

    @staticmethod
    def make_wrench_msg(
        wrench: np.ndarray,
        frame_id: str = "base_link",
        stamp=rospy.Time(),
    ) -> WrenchStamped:
        """Creates a WrenchStamped message from a numpy array."""
        msg = WrenchStamped()
        msg.header.stamp = stamp
        msg.header.frame_id = frame_id
        msg.wrench = numpy_to_wrench(wrench)
        return msg

    @staticmethod
    def make_double_rotation(R: np.ndarray) -> np.ndarray:
        """Creates a double rotation matrix from a rotation matrix. This
        is useful to rotate two vectors in a single operation.
        """
        R2 = np.zeros((6, 6))
        R2[:3, :3] = R2[3:, 3:] = R
        return R2

    def trajectory_cb(self, msg: PoseTwistStamped) -> None:
        """Callback for the trajectory topic to get the desired state."""
        with self.lock:
            self.desired_position, self.desired_orientation = pose_to_numpy(
                msg.posetwist.pose,
            )
            body_to_world = self.make_double_rotation(
                quaternion_matrix(self.desired_orientation),
            )
            self.desired_twist_world = body_to_world.dot(
                np.hstack(twist_to_numpy(msg.posetwist.twist)),
            )

    def odom_cb(self, msg: Odometry) -> None:
        """Callback for the odometry topic to get the current state."""
        with self.lock:
            self.body_frame = msg.child_frame_id
            self.global_frame = msg.header.frame_id
            (
                (self.position, self.orientation),
                (linvel, angvel),
                _,
                _,
            ) = odometry_to_numpy(msg)
            self.body_to_world = self.make_double_rotation(
                quaternion_matrix(self.orientation),
            )
            self.world_to_body = self.body_to_world.T
            self.twist_body = np.concatenate((linvel, angvel))
            self.twist_world = self.body_to_world.dot(self.twist_body)
            self.update()


if __name__ == "__main__":
    rospy.init_node("adaptive_controller")
    Sub8AdapativeController()
    rospy.spin()
