---
# yamllint disable-line rule:line-length
camera_topic: /camera/front/right/image_rect_color  # Image topic to use to find buoys
# yamllint disable-line rule:line-length
min_observations: 8  # Observations needed to attempt a least squares position estimate
# yamllint disable-line rule:line-length
min_contour_area: 0.001  # Minimum of image area contour must be to not be rejected
# yamllint disable-line rule:line-length
max_velocity: 1  # Highest velocity sub can be moving as in m/s before observations are ignored
max_circle_error: 0.03  # Maximum error from CircleFinder.verify_contour
# yamllint disable-line rule:line-length
min_trans: 0.05  # Smallest movement of sub in meters between observations to count towards observation count
# yamllint disable-line rule:line-length
timeout_seconds: 2.5  # Time in which min_observations must be seen to be considered found
# yamllint disable-line rule:line-length
roi_y: 0.2  # Proportion of top of frame to crop off, to avoid surface reflection
# yamllint disable-line rule:line-length
roi_height: 0.1  # Proportion of bottom of frame to crop off, to avoid ground reflection/noise
debug:
    ros: true  # Publish marker and mask topics for debugging
    cv: false  # Create OpenCV GUI windows with sliders for thresholds, etc
